export const description = [
    '',
    'While on duty, habitually leaving work assignment or work areas without permission from his immediate superior. (Established practices such as coffee breaks, lunch periods, etc. are excluded from this rule).',
    'Failure to comply with the scheduled break without justifiable reason',
    'Failure to keep work area clean and in order; Littering; Posting written materials in work area of on Bulletin Boards that is not work related',
    'Engaging in horseplay or disorderly conduct in the workplace that may disrupt the operations of the company or create annoyance to another employee.',
    'Maligning, making discriminatory remarks, uttering obscene and offensive and/or intriguing remarks against the person or honor of another employee which tends to cast dishonor, discredit.',
    'Acts of immorality or indecent exposures within the company premises or outside while on duty',
    'Influencing, persuading and or participation in a disturbance resulting in the disruption or delay in operations',
    'Offering, soliciting or accepting bribes, whether in money or in kind, in connection with one’s work',
    'Smoking within company premises which includes electronic cigarette',
    'Gambling, betting, conducting lotteries or other similar acts during working hours, within company premises or company sponsored activities',
    'Soliciting and collecting monetary contribution during working hours or within the company premises without written approval from the head of department or center lead',
    'Challenging or engaging in a fight, uncontrolled temper or discourtesy with your colleague, supervisor or any members of the management or any conduct unbecoming of a decent TBS employee',
    'Quarrelling and or fighting within the premise of the company',
    'Violation of the policy on receipts and solicitation on gifts and gratuities',
    'Speaking in vernacular and or violation to the English Only Policy while acting in the performance of the assigned duties or conducting company business.',
    'Failure to act on an infraction by a Supervisor or Manager to offenses under the Code of Discipline.',
    'Improper/non-accomplishment of reports or documents relative to the employee’s duties and responsibilities. PROVIDED that FALSIFICATION, TAMPERING, and or other types of misrepresentation in any document or report shall be penalized with DISMISSAL.',
    'Eating in areas other than those designated by the company.',
    'Putting-up or distributing unauthorized posters or messages on bulletin boards or in similar places or distributing such materials within the company premises.',
    'Use of company facilities or equipment for personal business or purpose resulting in additional expense or damage to the company.',
    'Insulting, being discourteous or rude to any Company officer, co-employee, or clients, within the premises of the Company or while the latter are discharging official functions.',
    'Failure or refusal to cooperate with others in completion of task or project',
    'Circulating rumors and/or derogatory stories/remarks against another person or against the company (whether true or not) at any time inside company premises, during company initiated activities or while on scheduled shift.',
    'Restraining, coercing, with threat or intimidation, another employee from testifying during administrative investigation.',
    'Failure or refusal to cooperate or testify in Company investigations unless the employee himself is under investigation and his testimony will infringe upon his Constitutional right against self-incrimination for a criminal offense.',
    'Engaging in usurious and/or money lending business while at work or inside company premises, including parking areas and pantries.',
    'Inciting distrust and discontent in the company.',
    'Losing or misplacing records, documents or proprietary property of the company which are prejudicial to the interests of the Company',
    'Any lewd acts inside the company premises or while on scheduled shift.',
    'Acceptance of gifts from guests, supplier, vendor or clients for personal gain regardless of the amount or its equivalent.',
    'Failure to liquidate cash advances within the required period from the fulfillment of the activity or event for which the cash advance was made. PROVIDED that “KITING”, embezzlement, malversation or misappropriation of company funds shall be penalized with DISMISSAL.',
    'Any act constituting theft or robbery or any attempt to commit theft or robbery of any property within or outside Company premises',
    'Committing retaliatory acts against any employee for reporting a possible violation of the employee handbook and other related policies and/or participating, regardless of degree of participation, in company initiated investigations.',
    'Excessive Infractions - Cumulative infractions of any kind recon from the date of first recorded infraction within a year. This includes, but not limited to, violations against account-specific rules and special policies.',
    'Refusal to render overtime without valid reason when the exigency of the work requires it',
    'Participation in another business engagement or outside employments without prior consent of the Company',
    'Failure, refusal or disregarding the submission of secondary requirements thirty (30) days upon being hired from the company. If still under training, employee shall be automatically remove from the roster and be included in the batch of training',
    'Concealing defective work, whether resulting in prejudice to the company or not',
    'Knowingly furnishing false, misleading or grossly inaccurate data or information to persons  duly authorized to receive the same, arising out of the employee’s negligence or failure to discharge his duties to make personal research, investigation or verification which acts causes prejudice to the company',
    'Bringing pornographic materials within the premises of the Company',
    'Willful disobedience and/or Gross Insubordination by the employee of the lawful orders of his superior',
    'Willfully holding back, slowing down, hindering or limiting work output',
    'Substituting company property, materials, or equipment with another of inferior quality or lesser value',
    'Bringing mugs/cups/containers into the work area without spill proof lids.',
    'Eating and or bringing of food into the work area without appropriate approval by management',
    'Improper use and care of company property including company facilities',
    'Tailgating',
    'Piggybacking',
    'Any other acts or causes analogous to the foregoing',
    'Selling merchandizes or anything of value during office hours inside company premises',
    'Failure or blatant refusal of an employee to an inspection conducted by an authorized security personnel',
    'Smoking in prohibited areas',
    'Unauthorized possession master key, which can open lockers, drawers, disks, cabinet, rooms and offices. However, actual use of master key, which can open lockers, drawers, disks, cabinet, rooms and offices, will lead to dismissal',
    'Using another employee’s ID card or access card to enter company premises, or to obtain benefit (whether from the company or the client).',
    'Unauthorized reproduction or simulation of company ID, access badge, or similar access pass (e.g. car pass)',
    'Unauthorized displacement, movement or transferring of any IT related equipments issued by the company.',
    'Deliberate tampering of fire alarm or security system causing disturbance or unecessary panic inside company premises. Provided that the disturbance caused unecessary financial impact to the company the penalty would be dismissal',
    'Refusal or failure to submit to an annual physical exam or treatment that may be prescribed by the company physician or company HMO accredited doctor as follow-up to the results of the annual medical check-up',
    'Refusal to receive treatment, medication prescribed by the company physician or accredited physician for an illness or disease that is inimical to the interest of the employees or operations. In this case, the employee will be asked to go on sick leave for the treatment. If the disease will need prolonged treatment, the provision of the law will apply. Should the employee refuse to comply with the instructions the penalty for insubordination may be imposed.',
    'Refusing to submit to a reasonable suspicion or random drug test when required.',
    'Possession or conspiring to bring illegal drugs onto company property, whether during working time or not.',
    'Refusal to undergo drug testing, rehabilitation and or treatment',
    'Failure to keep and maintain sanitation standards within the premises of the Company.',
    'Failure to comply with the prescribed procedure of sickness or personal injuries sustained at work or in cases of accidents involving Company vehicle, equipment or other Company proper',
    'Discussing topics of an obscene or harassing nature via e-mail,  instant messaging systems, and other on-line/real time web based office communications systems.',
    'Use of abusive, offensive, defamatory, threatening, offensive, bigoted, hateful or racially offensive statements in e-mail or messenger, instant messaging systems, and other on-line/real time web based office communications systems.',
    'Use of company computers or other electronic devices for hacking or cracking (unauthorized access into or interference in a computer system/server or information and communication system) and/or storing unlicensed, pirated or crack version of duly licensed and/or copyrighted materials.',
    'Producing, using, possessing, or trafficking one or more counterfeit access devices with the use of company computers, electronic devices, equipment, or tools.',
    'Using an unauthorized access device or conspiring with any employee to use an unauthorized access device whether or not within the performance of official job duties',
    'Inducing, enticing, permitting or in any manner allowing another employee, for a consideration or otherwise to produce, use, or traffic any counterfeit or unauthorized access devices, or access devices fraudulently applied for.',
    'Using, possessing, or trafficking any access code or numbers given by or obtained from the client/customer, whether or not for personal benefit and gain.',
    'Obtaining money or anything of value from the company or its clients and customers through the use of an access device obtained in the course of employment, with intent to defraud or with intent to gain with or without the intention of fleeing thereafter.',
    'Making any alteration, without the access device holder’s authority, of any amount or other information stated on the account.',
    'Obtaining money or anything of value through the use of an access device, with intent to defraud or with intent to gain and fleeing thereafter;',
    'Having in one’s possession, without authority from the owner of the access device or the access device company, an access device, or any material, such as slips, paper, notepad, carbon paper, or any other medium, on which the access device is written, printed, embossed, or otherwise indicate',
    'Deliberate intent to tamper, distribute or bypass  network and information systems security controls through the use of proxy, script, program, code or other similar protocols',
    'Rendering services for another employer or personal client during working time, without the knowledge or approval from the management',
    'Calling in sick or extending sick leave in order to obtain sick leave for other purposes',
    'Giving false names to customer, client or caller to avoid identification or customer complaints',
    'Knowingly giving false or misleading information or documents to seek or qualify for any preference and or benefit from the company',
    'Cheating during training and or examination ',
    'Any form of misrepresentation of Company causing or resulting to negativity to client',
    'Any form of incorrect tagging and or documentation of a transaction',
    'Any form of manipulation of productivity records, systems, data and or report  to improve metrics, performance ratings, or to earn incentives',
    'Any other acts or causes analogous to the foregoing',
    'Introducing, conducting unauthorized activities, personal business, selling and or any unnecessary undertaking such as watching TV, playing, sending irrelevant emails, text messages, reading unnecessary materials during official working hours and or premises without due permission from the management',
    'Unauthorized use of company issued telephones/mobile phones to make personal calls on company time without proper permission or authorization',
    'Sleeping while on duty',
    'Infidelity in the custody of documents by the employees entrusted with the care and custody of said documents',
    'Spying or maliciously obtaining information from the company confidential records, for purposes of discrediting the company or transmitting the same to others to the prejudice of the company',
    'Inducing, pressuring, influencing or bribing others to spy or obtain information for the purpose of discrediting the company or transmitting the same to others to the prejudice of the company',
    'Making false or malicious statements concerning the good name of the company and its products and services.',
    'Revealing or issuing without authority, confidential data, information, reports or similar documentation, or trade secret of the company to persons not authorized to receive them',
    'All other acts that violate the confidential nature of his employment which may cause or tend to cause damage or prejudice to the company',
    'Failure to take disciplinary action without justifiable reason',
    'Any other acts or causes analogous to the foregoing',
    'Abuse of discretion amounting to lack or abuse of authority that causes or tend to cause damage and prejudice to the company',
    'Maligning and or intriguing against the person or honor by a superior to his/her subordinates which tends to cast dishonor, discredit or contempt, upon the latter.',
    'Giving illicit, unlawful and immoral orders by a superior to his/her subordinate.',
    'Coercing or compelling a subordinate to do illicit, unlawful and immoral acts that may cause or tend to cause damage to the company.',
    'Keeping his subordinate as mistress or concubine or otherwise engaging in relationship that is abuse of power of conflict of interest',
    'Taking undue advantage by the superior of his position to compel a subordinate to perform any work or activity outside of the company for his/her personal gain and benefit',
    'Forcing a subordinate to resign',
    'Bringing of cellular phones (with or without camera), diskettes, flash or thumb drives, storage discs, MP3/MP4 players and other multimedia varieties, camera, digital cameras, video cameras, Bluetooth and other wireless storage and communication devices, pencil or pen, camera, writing pad or any similar storage devices on the production floor at any time. However, where the storage device is used to obtain confidential data and information, DISMISSAL shall be imposed.',
    'Failure to erase or delete notes, data, numbers, records or any personally identifiable information placed, pasted, or stored in Windows NOTEPAD, local, share drive, sharepoint or other similar web based information systems, immediately before logging off.',
    'Downloading, uploading, saving or transmitting unauthorized files, including but not limited to MP3 files and similar data, from the internet.',
    'Offering or soliciting material/s which might be deemed illegal, indecent or obscene or posting or transmitting unauthorized advertisements, promotions or solicitations. Posting or transmitting chain letters or similar e-mail messages.',
    'Subscribing to mailing list in the internet or downloading materials which contains indecent, obscene or illegal content.',
    'Initiating and/or downloading Network games, whether or not it may affect the performance of the company’s network and systems.',
    'Transmitting libelous, slanderous, threatening or abusive messages, through company provided e-mail and similar facilities, that may tend to cast dishonor in the name or integrity of another employee or officer, whether the same is true or not.',
    'Piracy or the unauthorized reproduction, dissemination, importation, use, removal, substitution, modification, storage, uploading, downloading, communication, or making available to the public, of protected material, electronic signature or copyrighted works.',
    'Discrimination of race, culture, religion, gender, origin, sexual orientation, age, natural origin while in a call or email',
    'Vandalism, deliberate tampering, defacing, damaging, or destruction of company property, without prejudice to restitution or replacement of the thing damaged or lost',
    'Leaving entrances, pedestals and computer monitors open, thus exposing it to unnecessary security risk',
    'Concealing disease or illness which endangers the health or safety of other employees',
    'Reporting to work under the influence of a controlled substance',
    'Possession of equipment, instrument, apparatus and other paraphernalia  used in the administration of dangerous/illegal drugs',
    'Using illegal drugs on company property',
    'Knowingly and willfully consenting to the unlawful acts provided for in this policy and uses his/ her influence, power or position in shielding, harboring, screening or facilitating the escape of any employee who has violated the provisions of this policy in order to prevent the arrest, prosecution or conviction',
    'Violation of safety rules and regulations posted by the company or general safety practices in the performance of work or in the use of company facilities for any purpose.',
    'Failure to prevent and/or report loss of company property, spoilage, wastage of resources within 24 hours resulting to loss to the Company',
    'Unauthorized release of Company equipment, files, records, documents or properties',
    'Misappropriating, withholding funds or failure to account for any funds, money of whatever amount and or property belonging to the company, whether for personal gain or not',
    'Receiving kickbacks or profits in transactions while representing TBS',
    'Making false claims for reimbursement, false  statements in employment records, false testimony in company investigations  and or any form of forgery',
    'Falsification of, or tampering with other Company records, instruments, documents or forging signature of company officials',
    'Conniving with or leading employees, superiors, customers, competitors or third person to defraud the company or its clients',
    'Attempted, frustrated or consummated theft or robbery of company property or property belonging to another person or employee within company premises.',
    'Obtaining loans or credit by using another employee’s identity without his consent.',
    'Engaging in the same business activities that are of the same nature with the operations or business of the Company.',
    'Use of customer information to commit computer theft and other  related acts of fraud whether inside or outside company premises.',
    'Committing other acts of dishonesty and fraud where there is a clear intent of personal gain, and the dishonest or fraudulent act is prejudicial to the guest, outside agency, supplier, officer, or other employees and personnel of TBS, or the dishonest  or fraudulent act is done to avoid responsibility  or serious consequence',
    'Using fictitious name or another employee’s name for the purpose of concealing an offense or evading responsibility',
    'Misrepresentation of product information to close a sale',
    'Tagging of sales and fee waiver to manipulate statistics',
    'Buddy punch-in or logging-in or logging-out for another employee regardless of time, place and circumstance',
    'Falsifying or tampering timecards, time keeping punches, or any other time keeping records and/or drawing salary/allowances by virtue of falsified time records.',
    'Failure to report within seventy-two (72) hours after one has received pay with erroneous payment or overpayment of salary, commission, allowance or any other form of remuneration or reimbursement',
    'Charging overtime work for more than what was actually rendered or for work, which is not considered as overtime',
    'Unauthorized commission, i.e., accepting directly or indirectly any sum of money, benefits in kind, unauthorized commission, offer or promise, in consideration of any act, contract, decision or service connected with the discharge of the employee’s official duties. This also includes granting of such commissions.',
    'Offering, soliciting or accepting bribes, whether in money or in kind, in connection with one’s work',
    'Making false claims for reimbursements, false statements in employment record, false testimony in Company investigations and/or any form or dishonesty and forgery',
    'Knowingly giving false or misleading information or documents to seek or qualify for any employment preference or benefit from the company',
    'Falsification of, or tampering with other Company records, instruments, documents or forging signature of Company Officials',
    'Simple negligence. Minor negligence which would not result to any significant losses by the company or to financial operations',
    'Gross and habitual neglect of duty. Is the absence of or failure to exercise required care or diligence or blatant disregard of the established rules and regulations or applicable standard of care, thereby causing or about to cause loss or damage to the company or damage or injury to others. Four (4) repeated acts of simple negligence, regardless of the nature of prior offenses, shall be considered gross and habitual and shall be dealt with DISMISSAL',
    'Failure to liquidate cash advances within the required period from the fulfillment of the activity or event for which the cash advance was made.',
    'Hiding, losing or misplacing records, instruments, papers, deeds and documents of the company which causes prejudice to the company',
    'Any employee responsible for the failure of the Company to comply with any government reportorial requirement shall be liable for the penalty imposed on the Company by the concerned government agency. Provided that the penalty imposed should it be necessitate to grave offense shall automatically constitute DISMISSAL.',
    'Negligence resulting in loss, wastage or spoilage of Company asset(s) in an amount not exceeding P5,000.00',
    'Negligence or carelessness resulting in loss, wastage or spoilage of Company asset(s) in an amount exceeding P10,000.00.',
    'Utterance of invectives, obscene, offensive and insulting words or willful disrespect by the superior on the honor or person of his subordinate.',
    'Performing an act by a superior to his/her subordinates, which tends to cast dishonor, discredit or contempt, upon the latter.',
    'Rendering services for another employer or personal client during working time, without the knowledge and consent of the Company',
    'Conniving with or inducing employees, superiors, customers, competitors or third person to defraud or otherwise prejudice the company or to commit an offense under established rules and regulations of the Company',
    'Engaging in the same business activities that are of the same nature with the operations or business of the Company',
    'Participation or involvement in any business transaction involving any person or business enterprise with which the company has commercial dealings',
    'Conspiracy to commit any of the above mentioned offenses',
    'Entering or agreeing with a competitor to boycott a particular product or entering an agreement with a vendor that limits the vendor’s sales to any of our competitors',
    'Offer, give or do anything that would compromise, or appear to compromise, the recipient’s ability to make fair and balanced business decisions, especially but not limited to government officials',
    'Insider trading, which can be committed by an employee with material, non-public information about any company to buy or sell securities, such as stocks and options, of that company, or to provide that information to someone else so that they may act upon it',
    'Being the subject of an Executive, customer or client complaint which once validated proves misconduct',
    'Failure to follow the specific account requirement on proper security verification questions prior to providing information',
    'Non-compliance to all business related audit required by the account',
    'Any form of posting or uploading of confidential information in any social networking/online site, including but not limited to production facilities, client names, client-specific processes, company tools.',
    'Utilizing the systems and tools to process any transaction (financial or not) on an employee’s own account.',
    'Utilizing the systems and client tools to look at a customer (whether or not celebrity or famous) or employee account, where the employee had no acceptable business reason/purpose for viewing the account',
    'Failing to verify/obtain security information prior to discussing account specific/critical account information with a customer',
    'Failure to notate or provide documentation during a call, email or chat conversation',
    'Gross negligence in the performance of assigned task/duties or serious dereliction of duty.',
    'a.      (1) One day of NCNS/ AWOL or unauthorized absence',
    'b.      (2) Two consecutive days or in a month of NCNS/ AWOL or unauthorized absences',
    'c.      (3) Three consecutive days or in a month of NCNS/ AWOL or unauthorized absences',
    'In the event that the employee will be absent on any given day, it is a requirement to inform the Immediate Supervisor and or Manager for each instance of absence 3 hours prior to the start of the shift.',
    'Non-disclosure of romantic, consanguinity or affinity relationship to any subordinate. Relationship by affinity and consanguinity with in third civil degree must be disclosed',
    'Call, Chat or e-mail avoidance or dropping of call/transaction, which may fall under any or similar to the following scenarios, to wit:',
    'a) Failure to answer calls, e-mail or chat conversation within the threshold period.',
    'b) Failure to answer at the start of the call, mail or chat conversation until the caller hangs up or leaves, as the case may be',
    'c) Intentional disconnection by the employee of the call, mail or chat conversation of the customer',
    'd) Transferring a call, mail or chat conversation back to the queue without valid reason',
    'e) Prematurely transferring a call, mail or chat conversation back to another department, associate, second level associates, resolution or escalation associate, or back to the queue.',
    'f) Intentionally giving inaccurate information in order to release a call, mail or chat conversation.',
    'g) Refusal to take a call or e-mail or chat without justifiable reason',
    'h) Intentionally placing a customer on hold, beyond the threshold period without good reason until the customer hangs-up or leaves.',
    'i) Aux Jumping: manipulating aux states to avoid calls in the queue',
    'j) Staying on the line upon transfer of the call to the next level of support beyond the threshold period',
    'k) Blatant disregard in providing resolution to customer or unwillingness to assist the customer with their concern',
    'l) Any act analogous to the foregoing',
    'Refusal to escalate calls when a customer has requested to speak to a manager',
    'Not reciting client prescribed disclosure verbatim',
    'Deliberate form of sharing/ disclosure of any client/ customer data/ PII issue/ Information to unintended party',
    'Unauthorized use of Aux codes like but not limited to  misuse of queue and issues codes/ status resulting to good performance',
    'Discourtesy to clients/ customers/ rude behavior/ sarcasm',
    'Use of profanity while in a call and or while inside the production floor',
    'Unprofessional conversation similar to mimicking/ mocking customers accent and voice',
    'Shouting at the customer and or utterance of obscene, offensive rude, sarcastic remarks, disrespectful and or consistently interrupting the customer in a rude manner',
    'Disregarding, forgetting or failure to log-in or log-out in any time keeping systems of the company',
    'Abuse of Aux or the use of aux beyond the prescribed time of the immediate Supervisor or Manager',
    'Failure to wear identification cards inside the offices of the Company which shall refer to the Corporate Office and other all offices of the Company where it may conduct business.',
    'Failure to inform the HR Department of the necessary changes of employee information within seven (7) calendar days upon knowledge of the changes',
    'Damaging or destruction of company property which includes vandalism, tampering, defacing and etc.',
    'Possession by an employee of explosives, firearm or deadly weapon within the company premises.',
    'Willful disobedience by the employee of the lawful orders of his superior',
    'Engaging in scandalous or malicious acts within the premises of the Company without material injury or damage to the Company, co-employees or clients thereof.',
    'Unauthorized entry to specified areas of the Company',
    'Allowing another to use his/her ID card or access card to enter company premises, or to obtain benefit (whether from the company or the client).',
    'Bringing or possession of alcoholic beverages on company premises whether during working time or not. Company premises for purposes of this provision refer to any company provided facilities, rooms, such as staff house and event centers, while on official out-of-place travel or work. Cars and personal vehicles shall not be considered as part of company premises for purposes of this provision.',
    'Drinking, tasting, sipping alcoholic beverages and/or reporting to any company premises and/or event under the influence of alcoholic beverages.',
    'Any act constituting threat, verbal assault, provocation, intimidation, coercion or harassment against any employee or in a manner unduly interfering with obstructing Company operations or other employees from performing their work within the Company premises.',
    'Using fictitious name or using another employee’s name for purposes of concealing an offense or evading responsibility',
    'Inflicting bodily injury, or the attempt thereof, upon others within the premises of the Company',
    'Under the pretense of official position, performing any act pertaining to any person in authority in the company, or any of its department, without being officially entitled to.',
    'Obtaining supplies or materials on fraudulent orders or connection and/or collusion with principal violators of the same either as a conspirator or as an accessory or an accomplice',
    'Falsification of expenses, i.e., any act of dishonesty or attempt to commit dishonesty or falsify a travel expense report, receipt or any other document upon which reimbursement is based on collecting said expense, making it appear an amount bigger than what was actually spent or disbursed',
    'Performing certain acts binding the Company or entering into transaction with any person, banking institution or any Company involving the Company of its interest without authority or in such manner, as it would constitute grave abuse of authority or discretion and contrary to Company policy',
    'Conviction for criminal acts involving moral turpitude and crimes, which, by its nature and consequences, adversely affects the employee’s performance or qualifications to remain an employee.',
    'All other acts of dishonesty which cause or tend to cause prejudice to the company',
    'Lending or sharing of password, access badge or similar access devices to another employee',
    'Transmitting or uploading materials that contain viruses, Trojan Horses, worms or any other harmful or deleterious programs.',
    'Unauthorized access or attempt to access security systems.',
    'Unauthorized download, upload or saving of executable files, such as Mozilla Firefox. Google Chrome and similar non-standard company browsers, flash players and the likes.',
    'Any access to corrupt, alter, steal, or destroy using a computer or other similar information and communication devices, including the introduction of computer viruses and the like, resulting in the corruption, destruction, alteration, theft or loss of electronic data messages or electronic document.',
    'Trafficking inside the company premises, one or more unauthorized access devices or access devices fraudulently applied for.',
    'Effecting transaction, with one or more access devices issued to another person or persons, to receive payment or any other thing of value.',
    'Disclosing any information about any access device, such as, but not limited to, the account number or name or address of the device holder, without the latter’s authority or permission.',
    'Conspiracy to commit any of the offenses mentioned above',
    'Slight sexual harassment includes but not limited to displaying offensive pictures or publications in the workplace and or company sponsored activities',
    'Less serious or less grave infractions including but not limited to persistently telling dirty jokes to a co-employee who has indicated finds them offensive. Taunting co-employee with constant talk of sex or sexual innuendos; asking a co-employee intimate questions on his or her sexual activities; making offensive hand or body gestures at a co-employee, staring or leering at a co-employee; making obscene phone calls to a co-employee ',
    'Serious or grave infractions including but not limited to pinching, unnecessarily brushing up against a co-employee’s body; touching a co-employee in sensitive  parts of his /her body, threats of  a sexual nature and actual sexual assault, etc.',
    'Any form of sexual harassment as defined in Republic Act No. 7877 – Anti Sexual Harassment Act of 1995, or under any other applicable law.',
    'A tardy can occur if an employee is not punctual and are late for the work shift or returning from your meal period or break',
    'Undertime',
    'Accessing unauthorized websites inside the production floor while on duty. Unauthorized websites are those websites which are not approved or certified by the Company. This shall include websites, including but not limited to social networking sites, blogs, and other similar sites.',
    'Forgeries and spoofing (IP, e-mail, etc.).',
];